# Generated by Django 2.1.5 on 2019-02-09 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog2',
            old_name='bodys',
            new_name='body',
        ),
    ]
